In [2]:
import torch
print(torch.__version__)

2.10.0+cu128


In [3]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


#Creating a Tensor


In [6]:
#using empty ---------- it just allocate memory but no value is currently saved there
a = torch.empty(2,3)
a

tensor([[2.5086e-30, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [7]:
#check type
type(a)

torch.Tensor

In [15]:
#using zeros
a = torch.zeros(2 , 3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [18]:
# using rand
torch.rand(2,3)

tensor([[0.1327, 0.5895, 0.6956],
        [0.3094, 0.4272, 0.7131]])

In [20]:
# use of seed
torch.rand(2,3)

tensor([[0.8844, 0.7832, 0.6962],
        [0.0073, 0.0419, 0.5100]])

In [22]:
# manual seed ------------ if someone wants to use my code and they want the exact random numbers ,
# i will have to use manual seed so they can use it later , it will generate the same random numbers each time

torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [23]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [26]:
# using tensor
torch.tensor([[2,3],[4,5]])

tensor([[2, 3],
        [4, 5]])

In [31]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,11))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [32]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [33]:
x.shape

torch.Size([2, 3])

In [34]:
torch.empty_like(x) #--- creates new matrix of x shape

tensor([[139141306191136,        11664816, 139135291206048],
        [139141308564800,        11664528, 139135291206096]])

In [35]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [42]:
torch.rand_like(x , dtype= torch.float32) # we need to specify dtype because x is of int64 and rand generate floats

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

#Tensor Data Types

In [44]:
# find data type
x.dtype

torch.int64

In [48]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [53]:
x


tensor([[1, 2, 3],
        [4, 5, 6]])

In [54]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Operations

###1. Scalar Operation

In [57]:
x = torch.rand(2,2)
x

tensor([[0.2426, 0.7003],
        [0.5277, 0.2472]])

In [58]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.0588, 0.4905],
        [0.2785, 0.0611]])

###2. Element Wise Operation

In [59]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.7909, 0.4235, 0.0169],
        [0.2209, 0.9535, 0.7064]])
tensor([[0.1629, 0.8902, 0.5163],
        [0.0359, 0.6476, 0.3430]])


In [60]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.1394, 0.4235, 0.0169],
        [0.0056, 0.3059, 0.0204]])

In [62]:
c = torch.tensor([1, -2, 3, -4])

In [63]:
# absolute
torch.abs(c)

tensor([1, 2, 3, 4])

In [65]:
# negative

torch.neg(c)


tensor([-1,  2, -3,  4])

In [67]:
d = torch.tensor([[1.2, 2.3 , 4.8 , 2.8]])
d

tensor([[1.2000, 2.3000, 4.8000, 2.8000]])

In [68]:
# round

torch.round(d)

tensor([[1., 2., 5., 3.]])

In [69]:
# ceil

torch.ceil(d)

tensor([[2., 3., 5., 3.]])

In [70]:
# floor

torch.floor(d)

tensor([[1., 2., 4., 2.]])

In [75]:
# clamp
torch.clamp(d, min=2, max=4)

tensor([[2.0000, 2.3000, 4.0000, 2.8000]])

###3. Reduction Operation

In [77]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[7., 9., 2.],
        [6., 7., 7.]])

In [78]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([18., 20.])

In [79]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([6.5000, 8.0000, 4.5000])

In [80]:
# median
torch.median(e)

tensor(7.)

In [81]:
# max and min
torch.max(e)
torch.min(e)

tensor(2.)

In [82]:
# product
torch.prod(e)

tensor(37044.)

In [83]:
# standard deviation
torch.std(e)

tensor(2.3381)

###4. Matrix Operation

In [89]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

#or

f = torch.randint(0 , 10, (2,3))  # torch.randint(low, high, (size))
g = torch.randint(0 , 10, (3,2))

print(f)
print(g)

tensor([[0, 2, 4],
        [4, 6, 2]])
tensor([[1, 0],
        [5, 1],
        [0, 0]])


In [90]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[10,  2],
        [34,  6]])

In [91]:
torch.matmul(g,f)

tensor([[ 0,  2,  4],
        [ 4, 16, 22],
        [ 0,  0,  0]])

In [92]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [93]:
# transpose
torch.transpose(f, 0, 1)

tensor([[0, 4],
        [2, 6],
        [4, 2]])

In [94]:
h = torch.randint(0,10,(3,3), dtype=torch.float32)
h

tensor([[2., 2., 3.],
        [7., 1., 5.],
        [0., 2., 3.]])

In [95]:
# determinant
torch.det(h)

tensor(-14.0000)

In [96]:
# inverse
torch.inverse(h)

tensor([[ 5.0000e-01,  2.2449e-08, -5.0000e-01],
        [ 1.5000e+00, -4.2857e-01, -7.8571e-01],
        [-1.0000e+00,  2.8571e-01,  8.5714e-01]])

###5. Special Functions

In [97]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[7., 0., 2.],
        [5., 2., 8.]])

In [98]:
# log
torch.log(k)

tensor([[1.9459,   -inf, 0.6931],
        [1.6094, 0.6931, 2.0794]])

In [99]:
# exp
torch.exp(k)

tensor([[1.0966e+03, 1.0000e+00, 7.3891e+00],
        [1.4841e+02, 7.3891e+00, 2.9810e+03]])

In [100]:
# sqrt
torch.sqrt(k)

tensor([[2.6458, 0.0000, 1.4142],
        [2.2361, 1.4142, 2.8284]])

In [101]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9991, 0.5000, 0.8808],
        [0.9933, 0.8808, 0.9997]])

In [102]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.8808, 0.1192, 0.0025],
        [0.1192, 0.8808, 0.9975]])

In [103]:
# relu
torch.relu(k)

tensor([[7., 0., 2.],
        [5., 2., 8.]])

###6. Inplace Operation

PyTorch tensors normally create new memory when you change them. In-place operations skip that. They modify the existing tensor directly instead of creating another one.

In [113]:
m = torch.tensor([1,2,3])
n = m + 1

print(m)
print(n)

#What happened?
#PyTorch created a new tensor for b. a stayed untouched.

tensor([1, 2, 3])
tensor([2, 3, 4])


In [116]:
a = torch.tensor([1,2,3])
a.add_(1)  #Instead of creating new memory, PyTorch just edits the existing tensor:

tensor([2, 3, 4])

In [117]:
a

tensor([2, 3, 4])

In [118]:
torch.relu(m)

tensor([1, 2, 3])

In [119]:
m.relu_()

tensor([1, 2, 3])

###7. Copying a Tensor

In [140]:
a = torch.randint(0,10,(2,3))
a

tensor([[7, 5, 6],
        [9, 8, 2]])

In [141]:
b = a

In [142]:
b

tensor([[7, 5, 6],
        [9, 8, 2]])

In [143]:
a[0][0]=0
a

tensor([[0, 5, 6],
        [9, 8, 2]])

In [144]:
b  # notice : b also changes but we dont want that , so another way is to clone it

tensor([[0, 5, 6],
        [9, 8, 2]])

In [145]:
print(id(a))
print(id(b))

139135256881792
139135256881792


In [152]:
b = a.clone()

In [153]:
print(a)
print(b)

tensor([[0, 5, 6],
        [9, 8, 2]])
tensor([[0, 5, 6],
        [9, 8, 2]])


In [155]:
a[0][0]=2
a

tensor([[2, 5, 6],
        [9, 8, 2]])

In [160]:
print(a)
print(b)

print("id of a ",id(a))
print("id of b",id(b))

# now b remains as it was , while a changes

tensor([[2, 5, 6],
        [9, 8, 2]])
tensor([[0, 5, 6],
        [9, 8, 2]])
id of a  139135256881792
id of b 139135257624656
